# Generated by Django 4.0.4 on 2022-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_raiting_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='Movie', max_length=255),
            preserve_default=False,
        ),
    ]
